steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build API Gateway'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/service-a:$COMMIT_SHA', './api-gateway']
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push API Gateway'
    args: ['push', 'gcr.io/$PROJECT_ID/service-a:$COMMIT_SHA']

  # Build and push Docker image for Service B
#  - name: 'gcr.io/cloud-builders/docker'
#    id: 'Build Service B'
#    args: ['build', '-t', 'gcr.io/$PROJECT_ID/service-b:$COMMIT_SHA', './service-b']
#  - name: 'gcr.io/cloud-builders/docker'
#    id: 'Push Service B'
#    args: ['push', 'gcr.io/$PROJECT_ID/service-b:$COMMIT_SHA']

  # Deploy Service A to Kubernetes
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'Deploy Service A'
    args: [
      'set', 'image',
      'deployment/service-a',
      'service-a=gcr.io/$PROJECT_ID/service-a:$COMMIT_SHA',
      '--namespace=default'
    ]

#  # Deploy Service B to Kubernetes
#  - name: 'gcr.io/cloud-builders/kubectl'
#    id: 'Deploy Service B'
#    args: [
#      'set', 'image',
#      'deployment/service-b',
#      'service-b=gcr.io/$PROJECT_ID/service-b:$COMMIT_SHA',
#      '--namespace=default'
#    ]

  # Deploy Service C to Kubernetes
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'Deploy Service C'
    args: [
      'set', 'image',
      'deployment/service-c',
      'service-c=gcr.io/$PROJECT_ID/service-c:$COMMIT_SHA',
      '--namespace=default'
    ]

# List of images to push to Google Container Registry
images:
  - 'gcr.io/$PROJECT_ID/service-a:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/service-b:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/service-c:$COMMIT_SHA'
