version: '3.1'

services:
  postgres-auth:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data/auth
    volumes:
      - postgres_data_auth:/var/lib/postgresql/data

volumes:
  postgres_data_auth:
    driver: local