name: Continuous Integration

on:
  push:
    branches:
      - pipeline-dev
  pull_request:
    branches:
      - pipeline-dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'maven'

      - name: Run all unit tests
        run: mvn -B test

